"""Add timezone to users

Revision ID: d32f6e15bf54
Revises: 7ee0b0b05b15
Create Date: 2025-12-30 21:02:38.563755

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'd32f6e15bf54'
down_revision: Union[str, Sequence[str], None] = '7ee0b0b05b15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
